// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: userrpc.proto

package userrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Userrpc_Ping_FullMethodName           = "/userrpc.Userrpc/Ping"
	Userrpc_UpdateBalance_FullMethodName  = "/userrpc.Userrpc/UpdateBalance"
	Userrpc_TranIn_FullMethodName         = "/userrpc.Userrpc/TranIn"
	Userrpc_TranOut_FullMethodName        = "/userrpc.Userrpc/TranOut"
	Userrpc_TranReverseIn_FullMethodName  = "/userrpc.Userrpc/TranReverseIn"
	Userrpc_TranReverseOut_FullMethodName = "/userrpc.Userrpc/TranReverseOut"
)

// UserrpcClient is the client API for Userrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserrpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error)
	TranIn(ctx context.Context, in *TranInRequest, opts ...grpc.CallOption) (*TranInResponse, error)
	TranOut(ctx context.Context, in *TranOutRequest, opts ...grpc.CallOption) (*TranOutResponse, error)
	TranReverseIn(ctx context.Context, in *TranInRequest, opts ...grpc.CallOption) (*TranInReverseResponse, error)
	TranReverseOut(ctx context.Context, in *TranOutRequest, opts ...grpc.CallOption) (*TranOutReverseResponse, error)
}

type userrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserrpcClient(cc grpc.ClientConnInterface) UserrpcClient {
	return &userrpcClient{cc}
}

func (c *userrpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Userrpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userrpcClient) UpdateBalance(ctx context.Context, in *UpdateBalanceRequest, opts ...grpc.CallOption) (*UpdateBalanceResponse, error) {
	out := new(UpdateBalanceResponse)
	err := c.cc.Invoke(ctx, Userrpc_UpdateBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userrpcClient) TranIn(ctx context.Context, in *TranInRequest, opts ...grpc.CallOption) (*TranInResponse, error) {
	out := new(TranInResponse)
	err := c.cc.Invoke(ctx, Userrpc_TranIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userrpcClient) TranOut(ctx context.Context, in *TranOutRequest, opts ...grpc.CallOption) (*TranOutResponse, error) {
	out := new(TranOutResponse)
	err := c.cc.Invoke(ctx, Userrpc_TranOut_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userrpcClient) TranReverseIn(ctx context.Context, in *TranInRequest, opts ...grpc.CallOption) (*TranInReverseResponse, error) {
	out := new(TranInReverseResponse)
	err := c.cc.Invoke(ctx, Userrpc_TranReverseIn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userrpcClient) TranReverseOut(ctx context.Context, in *TranOutRequest, opts ...grpc.CallOption) (*TranOutReverseResponse, error) {
	out := new(TranOutReverseResponse)
	err := c.cc.Invoke(ctx, Userrpc_TranReverseOut_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserrpcServer is the server API for Userrpc service.
// All implementations must embed UnimplementedUserrpcServer
// for forward compatibility
type UserrpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error)
	TranIn(context.Context, *TranInRequest) (*TranInResponse, error)
	TranOut(context.Context, *TranOutRequest) (*TranOutResponse, error)
	TranReverseIn(context.Context, *TranInRequest) (*TranInReverseResponse, error)
	TranReverseOut(context.Context, *TranOutRequest) (*TranOutReverseResponse, error)
	mustEmbedUnimplementedUserrpcServer()
}

// UnimplementedUserrpcServer must be embedded to have forward compatible implementations.
type UnimplementedUserrpcServer struct {
}

func (UnimplementedUserrpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedUserrpcServer) UpdateBalance(context.Context, *UpdateBalanceRequest) (*UpdateBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBalance not implemented")
}
func (UnimplementedUserrpcServer) TranIn(context.Context, *TranInRequest) (*TranInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranIn not implemented")
}
func (UnimplementedUserrpcServer) TranOut(context.Context, *TranOutRequest) (*TranOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranOut not implemented")
}
func (UnimplementedUserrpcServer) TranReverseIn(context.Context, *TranInRequest) (*TranInReverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranReverseIn not implemented")
}
func (UnimplementedUserrpcServer) TranReverseOut(context.Context, *TranOutRequest) (*TranOutReverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranReverseOut not implemented")
}
func (UnimplementedUserrpcServer) mustEmbedUnimplementedUserrpcServer() {}

// UnsafeUserrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserrpcServer will
// result in compilation errors.
type UnsafeUserrpcServer interface {
	mustEmbedUnimplementedUserrpcServer()
}

func RegisterUserrpcServer(s grpc.ServiceRegistrar, srv UserrpcServer) {
	s.RegisterService(&Userrpc_ServiceDesc, srv)
}

func _Userrpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userrpc_UpdateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).UpdateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_UpdateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).UpdateBalance(ctx, req.(*UpdateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userrpc_TranIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).TranIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_TranIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).TranIn(ctx, req.(*TranInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userrpc_TranOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).TranOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_TranOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).TranOut(ctx, req.(*TranOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userrpc_TranReverseIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).TranReverseIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_TranReverseIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).TranReverseIn(ctx, req.(*TranInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userrpc_TranReverseOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserrpcServer).TranReverseOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userrpc_TranReverseOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserrpcServer).TranReverseOut(ctx, req.(*TranOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Userrpc_ServiceDesc is the grpc.ServiceDesc for Userrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userrpc.Userrpc",
	HandlerType: (*UserrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Userrpc_Ping_Handler,
		},
		{
			MethodName: "UpdateBalance",
			Handler:    _Userrpc_UpdateBalance_Handler,
		},
		{
			MethodName: "TranIn",
			Handler:    _Userrpc_TranIn_Handler,
		},
		{
			MethodName: "TranOut",
			Handler:    _Userrpc_TranOut_Handler,
		},
		{
			MethodName: "TranReverseIn",
			Handler:    _Userrpc_TranReverseIn_Handler,
		},
		{
			MethodName: "TranReverseOut",
			Handler:    _Userrpc_TranReverseOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userrpc.proto",
}
