// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type CreateOrderRequest struct {
	Id          string  `json:"id"`
	Userid      int64   `json:"userid"`
	ShoppingId  int64   `json:"shoppingid"`
	Payment     float64 `json:"payment"`
	PaymentType int64   `json:"paymenttype"`
	Postage     int64   `json:"postage"`
	Status      int64   `json:"status"`
	Balance     float64 `json:"balance"`
}

type CreateOrderResponse struct {
	Message string `json:"message"`
}
