// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"awesomeProject7/users/userapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: UserapiHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update-balance",
				Handler: UpdateBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/tran-inout",
				Handler: TranInOutBalanceHandler(serverCtx),
			},
		},
	)
}
