// Code generated by goctl. DO NOT EDIT.
// Source: userrpc.proto

package server

import (
	"context"

	"awesomeProject7/users/userrpc/internal/logic"
	"awesomeProject7/users/userrpc/internal/svc"
	"awesomeProject7/users/userrpc/userrpc"
)

type UserrpcServer struct {
	svcCtx *svc.ServiceContext
	userrpc.UnimplementedUserrpcServer
}

func NewUserrpcServer(svcCtx *svc.ServiceContext) *UserrpcServer {
	return &UserrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserrpcServer) Ping(ctx context.Context, in *userrpc.Request) (*userrpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserrpcServer) UpdateBalance(ctx context.Context, in *userrpc.UpdateBalanceRequest) (*userrpc.UpdateBalanceResponse, error) {
	l := logic.NewUpdateBalanceLogic(ctx, s.svcCtx)
	return l.UpdateBalance(in)
}

func (s *UserrpcServer) TranIn(ctx context.Context, in *userrpc.TranInRequest) (*userrpc.TranInResponse, error) {
	l := logic.NewTranInLogic(ctx, s.svcCtx)
	return l.TranIn(in)
}

func (s *UserrpcServer) TranOut(ctx context.Context, in *userrpc.TranOutRequest) (*userrpc.TranOutResponse, error) {
	l := logic.NewTranOutLogic(ctx, s.svcCtx)
	return l.TranOut(in)
}

func (s *UserrpcServer) TranReverseIn(ctx context.Context, in *userrpc.TranInRequest) (*userrpc.TranInReverseResponse, error) {
	l := logic.NewTranReverseInLogic(ctx, s.svcCtx)
	return l.TranReverseIn(in)
}

func (s *UserrpcServer) TranReverseOut(ctx context.Context, in *userrpc.TranOutRequest) (*userrpc.TranOutReverseResponse, error) {
	l := logic.NewTranReverseOutLogic(ctx, s.svcCtx)
	return l.TranReverseOut(in)
}
