// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UpdateBalanceRequest struct {
	Id      int64   `json:"id"`
	Balance float64 `json:"balance"`
}

type UpdateBalanceResponse struct {
	Message string `json:"message"`
}

type TranInOutRequest struct {
	InId    int64   `json:"inid"`
	OutId   int64   `json:"outid"`
	Balance float64 `json:"balance"`
}

type TranInOutResponse struct {
	Message string `json:"message"`
}
